name: cutntag-pe-nextflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - nextflow>=24.10
  - fastqc
  - multiqc
  - cutadapt
  - bowtie2
  - samtools>=1.17
  - htslib
  - tabix
  - picard
  - umi_tools
  - bedtools
  - deeptools
  - macs3
  - homer
  - parallel
  - pandas
  - numpy
  - scipy
  - matplotlib
  - pybigwig
  - pyyaml

